/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package angelhack;

import javax.swing.JFrame;

/**
 *
 * @author Lenovo
 */
public class shooping_main_2 extends javax.swing.JFrame {

    /**
     * Creates new form shooping_main_2
     */
    public shooping_main_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Lady Beg ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 300, 64, 17);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/handbeg 2.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 190, 98, 99);

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("RM 3800");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 320, 64, 14);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("From Taobao.com");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 340, 86, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/handbeg 1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 190, 89, 99);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Lady Beg ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 310, 64, 17);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("RM 3000");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 330, 64, 14);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("From Zalora.com");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 350, 80, 29);

        jButton1.setText("Promotion ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 260, 100, 23);

        jButton2.setText("Zalora Zone");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 310, 107, 23);

        jButton3.setText("TaoBao Zone");
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 200, 107, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/black color.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 90, 250, 550);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Picture2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 450, 690);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red background.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 90, 150, 560);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/14518396-textured-blue-background.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -20, 620, 830);

        jButton4.setText("Share");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 380, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
           JFrame f1 = new shopping_main_page();
      f1.setVisible(true);
      f1.setSize(600, 1000);
        f1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          JFrame f1 = new zalora_shopping_page();
      f1.setVisible(true);
      f1.setSize(600, 1000);
        f1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFrame f1 = new groupchat1();
      f1.setVisible(true);
      f1.setSize(600, 1000);
        f1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shooping_main_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shooping_main_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shooping_main_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shooping_main_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shooping_main_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
