/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package angelhack;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Lenovo
 */
public class shopping_page extends javax.swing.JFrame {

    /**
     * Creates new form shopping_page
     */
    public shopping_page() {
        
        
        initComponents();
        jLabel2.setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Picture2.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shoe icon.jpg"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 190, 88, 90);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/handbag_icon.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 190, 95, 90);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cloth image.jpg"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 390, 88, 99);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/other icon.jpg"))); // NOI18N
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 380, 95, 106);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("SHOE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 280, 110, 60);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Hand Beg");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 290, 70, 34);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Other");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 490, 110, 60);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Cloth");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 490, 110, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/black color.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 80, 390, 560);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Picture2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 10, 450, 700);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/14518396-textured-blue-background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-16, -16, 630, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
          JFrame f1 = new shooping_main_2();
      f1.setVisible(true);
      f1.setSize(500, 1000);
        f1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
           JFrame f2 = new shopping_page();
      f2.setVisible(false);
      f2.setSize(1000, 500);
      f2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      
      this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shopping_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shopping_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shopping_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shopping_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shopping_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
